### ISSUE TITLE
highlighter removes all other highlighters of a DOM until refreshing the page

### ISSUE THREAD

**Issue by teobais** [jeromepl/highlighter#15]
Hi,

Thank you for this great extension.
Maybe an idea to look into the DOM manipulation of this extension? It seems that it overrules any other highlighters until and unless the page is refreshed.
[This gif](http://g.recordit.co/3nCt0fw48O.gif) showcases the issue.

Environment
- macOS Catalina 10.15.6
- Version 87.0.4280.88 (Official Build) (x86_64)

**Comment by jeromepl** [comment]
Hi,
Can you provide me with the name of an extension that doesn't work alongside this one?
In general it isn't possible to make this be compatible with every other extensions out there, especially since this relies a lot on the DOM being similar every time a page is refreshed, but I can take a quick look at the issue you are having and see if there is an easy solution

**Comment by thodorisbais** [comment]
Hey @jeromepl , it's beanote, but [as you can see](https://twitter.com/thodorisbais/status/1342939054376161294), I'm not able to provide a link to the extension's webpage this time.

**Comment by jeromepl** [comment]
Unfortunately I can't do anything about this without the extension in question, but I'll leave this issue up and maybe it will come back to the chrome web store at some point

**Comment by thodorisbais** [comment]
Sounds like a plan, @jeromepl , thanks!

**Comment by jeromepl** [comment]
Hi @teobais , I found Beanote on the chrome web stored and tried it alongside the latest version of Highlighter. There doesn't seem to be this issue anymore! Either one of the changes made to Highlighter or to Beanote since then must have resolved the issue 🙂
