### ISSUE TITLE
Multiple highlights pasted like a single paragraph

### ISSUE THREAD

**Issue by ujeshkrishnan** [jeromepl/highlighter#22]
I used to mark multiple sentences from a single blog post. 

Then I hit "Copy all" button in the extension and pasted in my notes. 

What happened is that, the whole texts pasted like a single paragraph instead of multiple short paragraphs.

This is causing additional manual work to separate the highlighted lines. 

I hope you'll fix it soon.

**Comment by jeromepl** [comment]
Hi @ujeshkrishnan , could you provide a bit more info about this issue you are facing?
When I use the "Copy all" button on a page where I have multiple highlights, the result of pasting is a bullet list of all the highlights. For example in microsoft word:
![image](https://user-images.githubusercontent.com/7671307/130513966-025366e4-8468-4c34-a1fa-ebc910249437.png)

**Comment by ujeshkrishnan** [comment]
I tried pasting on [Standard Notes](https://standardnotes.com/) & [Google Docs](https://www.google.com/docs/about/) but couldn't see it appear as bullet points. 

Browser: Brave
Device: MacBook Air

**Comment by jeromepl** [comment]
I just pushed a change to the way the "Copy All" button works.
In short, we now use `navigator.clipboard.writeText` instead of `document.execCommand("copy")`

I'm hoping this will fix the issue for both of you as this is not copy-pasting the HTML structure of the highlights in the popup anymore, but rather is simply copy-pasting the text, where each highlight is separated by a new line. In most text editors, if already within a bullet point list, this will result in one new bullet point per highlight

I will be releasing this as part of v4 in early January and will close this issue then :)
