### ISSUE TITLE
analytics.js is missing

### ISSUE THREAD

**Issue by omrihaim** [jeromepl/highlighter#4]
Defined as a background script in the manifest and missing in repository

**Comment by jeromepl** [comment]
This is intentional. That script is for google analytics and contains a private key that can't be shared.

Depending on what you want to do with this code, I would recommend either:
1) removing `analytics.js` from the list of background scripts in the manifest **and** commenting out [this line](https://github.com/jeromepl/highlighter/blob/c14612dff87fcb38820991e8dc1f38498e36aa5e/background.js#L72) in `background.js`
2) getting your own google analytics key and putting the [analytics tag](https://support.google.com/analytics/answer/6086097?hl=en) in a file named `analytics.js`
