### ISSUE TITLE
Privacy Policy

### ISSUE THREAD

**Issue by bowarmbold** [jeromepl/highlighter#5]
Do you have a Privacy Policy and or Terms of Service Document that we can look at to evaluate this extension for our Students? 

Thanks in advance,

**Comment by jeromepl** [comment]
Thanks for the interest in this extension!

I realize that a privacy policy was a missing piece of this extension since we do use Google Analytics. I went ahead and added one (which you can read [here](https://github.com/jeromepl/highlighter/blob/master/privacy_policy.md)).

In short, we do not collect browsing information such as the contents of highlights and URLs accessed by our user. We simply collect anonymous basic usage information such as which tools are used and through which menu they are accessed.

As for a Terms of Service document, we do not have one since we deem it to be unnecessary given the limited functionality this extension provides.
