### ISSUE TITLE
Questions regarding highlights storage

### ISSUE THREAD

**Issue by netrebel** [jeromepl/highlighter#7]
I'm guessing in a local storage that Chrome has.

What happens if I reinstall Chrome? Do I lose the highlights? 
If the webpage is changed and part of the highlighted text is gone, will it still highlight some of it? 

If it's a local storage, I'm guessing I'll have different sets of highlights having this Chrome plugin (automatically synced) across computers.

This info might be useful to have as part of the extension description in the Chrome store.

I find this plugin so useful to highlight documentation. Thanks 🙏

**Comment by jeromepl** [comment]
You guessed right, the highlights are stored in chrome local storage. I unfortunately couldn't use "sync" storage (which would be synced across your devices) since it didn't offer enough storage space (along with several other [restrictions](https://developer.chrome.com/apps/storage#property-sync)).
I'm not 100% sure what happens when reinstalling chrome on the same computer. Whether your highlights would stay depends on whether chrome deletes local storage or not when uninstalling.

I kept it simple for non technical people in the extension description by simply saying that this extension keeps highlights store "on your device". 😄

Thanks for the comments and feedback! I really would love for this extension to store highlights in some remote storage that would allow for syncing across devices but unfortunately that would require paying for server(s) and quite frankly I don't want to charge people for an extension as "rough around the edges" as this!

**Comment by LarryEitel** [comment]
Permit me please to reopen this 'issue'. 

Thank you very much for this useful tool.

As I work on a variety of devices, it would be a game-changer to be able to highlight text and have it synced across devices.

I am thinking that it 'might/should' be possible to create a tool to sync the highlight local-storage db to other devices. Perhaps import/export can be added. 'Worst-case' export highlights to cloud-drive and later import from cloud to another device/instance of highlighter.

Thank you for your kind consideration of this idea.

**Comment by gudh** [comment]
@jeromepl 

Can I export all my highlights at once?

cuz I don't want to risk losing all my highlights when reinstalling Chrome
